HDFGroup/HDFGroup.github.io

- documentation/index.md
Please capitalize M for CMake.
> Change Cmake to CMake

- documentation/hdf5-docs/registered_virtual_file_drivers_vfds.md
> Change HDF Groupv -> HDF Group

- documentation/hdf5-docs/registered_vol_connectors.md
This will render the VOL table properly on GitHub.
> docs: fix markdown table formatting

- documentation/hdf5-docs/registered_filter_plugins.md
I adjusted the one-line for zfp and added a link to zfp pages.
> Adjust zfp description

- documentation/hdf5-docs/release_specifics/api_comp_macros.md
Reverts HDFGroup/HDFGroup.github.io#140
> Revert "Fix format"

- documentation/hdf5-docs/release_specifics/sw_changes_1.10.md
Reverts HDFGroup/HDFGroup.github.io#151
> Revert "Fix internal links"

- documentation/hdf5-docs/release_specifics/sw_changes_1.10.md
Reverts HDFGroup/HDFGroup.github.io#150
> Revert "Try to fix internal links"

- documentation/hdf5-docs/release_specifics/sw_changes_1.10.md
- documentation/hdf5-docs/release_specifics/sw_changes_1.12.md
Reverts HDFGroup/HDFGroup.github.io#149
> Revert "Trying to fix internal links"

- documentation/hdf5-docs/release_specifics/api_comp_macros.md
- documentation/hdf5-docs/release_specifics/release_specific_info.md
Reverts HDFGroup/HDFGroup.github.io#146
> Revert "Fix file path"

- documentation/hdf5-docs/release_specifics/sw_changes_1.10.md
- documentation/hdf5-docs/release_specifics/sw_changes_1.12.md
> Format the Software Changes pages

- documentation/index.md
Use the Registered Filter Plugins md file in github
> Add hdf5_plugins-docs

- documentation/hdf5-docs/registered_filter_plugins.md
> Add filter detail per user's request

- documentation/hdf5-docs/release_specifics/sw_changes_1.14.md
- downloads/hdf5/hdf5_1_14_4.md
Also re-made the part of the previous releases
> Update pages for 1.14.4 release

- documentation/hdf5-docs/advanced_topics/file_image_ops.md
- documentation/hdf5-docs/advanced_topics_list.md
Reverts HDFGroup/HDFGroup.github.io#183
> Revert "Change md file to html"

- documentation/hdf5-docs/advanced_topics_list.md
- documentation/hdf5-docs/hdf5_topics/chunking_in_hdf5.md
- documentation/hdf5-docs/list_hdf5_topics.md
- copied chunking_in_hdf5.md to hdf5_topics because it belongs there; we will forward https://portal.hdfgroup.org/documentation/hdf5-docs/chunking_in_hdf5.html to https://portal.hdfgroup.org/documentation/hdf5-docs/hdf5_topics/chunking_in_hdf5.html Once that is done, remove hdf5-docs/chunking_in_hdf5.html
> Rearrange topics

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .vscode/settings.json
- _config-local.yml
- _layouts/default.html
- index.md
> Add index file and correct layout archive link.   Adding devcontainer config.

- 404.md
It would be nice to add a search box to the 404 page when the dust clears, but this is a very simple update for now.
> Minor 404 update

- documentation/hdf5-docs/release_specifics/new_features_1_14.md
- downloads/hdf5/hdf5_1_14_5.md
Fixed some links in 1_14_5 release page
Fixed HDF4/HDF5 typo in New features document (closes #322)
> Minor clean-up after 1.14.5 release

- documentation/index.md
> Update documenation index.md

- downloads/index.md
> Update Download index.md

- downloads/index.md
Fix formatting and add links for specific ftp archive locations.
> Lkurz patch 1
